### PR TITLE
Adds Team Section With Some Minor Changes

### PR DESCRIPTION
**Pull request by palletprotocol**
Adds team section in both English and Chinese (zh-cn) version with
photos of them. Removes zh-tw version currently. For further references,
please refer to pull request #25. Some minor incompatible code style has been fixed.
with style adjustments. Note that these photos will slow down the loading, and it
should be fixed in further version. We also need some browser compatible checks.

### CODE REVIEW

**Comment by palletprotocol** [comment]
Please help confirm the correctness of these changes

**Comment by Tony-HSU** [comment]
I found the sum of the size of all the team's photos is near to 1MB, I think we should first show the main part of our index and then delayed loading these photos.

**Comment by magrady24** [comment]
Due to the time constraints of this work, I hope to publish these new contents before optimizing these technology details. If there is no major issues, you can change it later.

**Comment by Tony-HSU** [comment]
OK, I agree that. We can try to merge it.

**Comment by magrady24** [comment]
@palletprotocol 
If you are sure that there is no major issue, you can merge it.

**Comment by palletprotocol** [comment]
@magrady24 I fixed a minor wrong. Merging now.

**Pull request merged**
